---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/jsztuka/infra-deployments
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-main
